from typing import Protocol, Dict, Any
from pathlib import Path

class Plugin(Protocol):
    id: str

    def prepare(self, src: str, tmpdir: Path, env: Dict[str, Any]) -> Dict[str, Any]: ...
    def explore(self, workdir: Path, outdir: Path, env: Dict[str, Any]) -> Dict[str, Any]: ...
    def journeys(self, flows: Dict[str, Any], outdir: Path, env: Dict[str, Any]) -> Dict[str, Any]: ...
    def stride(self, flows: Dict[str, Any], journeys: Dict[str, Any], outdir: Path, env: Dict[str, Any]) -> Dict[str, Any]: ...
    def generate_tests(self, flows: Dict[str, Any], journeys: Dict[str, Any], threats: Dict[str, Any], outdir: Path, env: Dict[str, Any]) -> Dict[str, Any]: ...
    def run_tests(self, outdir: Path, env: Dict[str, Any]) -> Dict[str, Any]: ...
    def extra_checks(self, workdir: Path, outdir: Path, env: Dict[str, Any]) -> Dict[str, Any]: ...
