version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: uatu-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: uatu_audit
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - uatu-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  dashboard:
    build: .
    env_file:
      - .env
      - dashboard.env
    entrypoint: []
    command: ["python3", "-m", "uvicorn", "auditor.dashboard.server:app", "--host", "0.0.0.0", "--port", "${DASHBOARD_PORT:-8080}"]
    ports:
      - "${DASHBOARD_PORT:-8080}:${DASHBOARD_PORT:-8080}"
    environment:
      SECRET_KEY: "${SECRET_KEY:-change-me-in-production}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY:-change-me-in-production}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      GITHUB_REDIRECT_URI: "${GITHUB_REDIRECT_URI:-http://localhost:8080/auth/callback}"
      OAUTH_CALLBACK_URL: "${OAUTH_CALLBACK_URL:-http://localhost:8080/auth/callback}"
      ALLOWED_GH_ORGS: "${ALLOWED_GH_ORGS:-}"
      ALLOWED_EMAILS: "${ALLOWED_EMAILS:-}"
      DASHBOARD_CACHE_TTL: "${DASHBOARD_CACHE_TTL:-10}"
      API_BASE_URL: "${API_BASE_URL:-http://localhost:8000}"
      FRONTEND_URL: "${FRONTEND_URL:-http://localhost:8080}"
      DATABASE_URL: "${DATABASE_URL:-sqlite:///./uatu_audit.db}"
      MONGODB_URL: "${MONGODB_URL:-mongodb://admin:password@mongodb:27017/uatu_audit?authSource=admin}"
      DEBUG: "${DEBUG:-false}"
      ENVIRONMENT: "${ENVIRONMENT:-production}"
      DEFAULT_AUDIT_PRICE_USDC: "${DEFAULT_AUDIT_PRICE_USDC:-200}"
      MAX_AUDIT_TIME_SECONDS: "${MAX_AUDIT_TIME_SECONDS:-30}"
      PAYMENT_PROVIDER: "${PAYMENT_PROVIDER:-base}"
      USDC_CONTRACT_ADDRESS: "${USDC_CONTRACT_ADDRESS:-0xa0b86a33e6ba83a6508b88d6c8a4e4ddb4cc6c44}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      AUDITS_ROOT: "audits"
      EXTRA_ROOTS: "out"
    volumes:
      - ./:/app  # mount entire project for live updates
    working_dir: /work
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - uatu-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DASHBOARD_PORT:-8080}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Auditor CLI Service (for running audits)
  auditor:
    build: .
    container_name: uatu-auditor
    env_file:
      - .env
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      AUDITS_ROOT: "/app/audits"
      EXTRA_ROOTS: "/app/out"
    volumes:
      - ./audits:/app/audits
      - ./out:/app/out
      - ./examples:/app/examples
      - ./tmp:/app/tmp
    networks:
      - uatu-network
    command: ["--help"]

volumes:
  mongodb_data:
  mongodb_config:

networks:
  uatu-network:
    driver: bridge
